 @baseUrl = http://localhost:3001/api/catalogos

### Get CATALOGOS GENERALES
GET http://localhost:3001/api/catalogosglobal/escolaridad
###
GET http://localhost:3001/api/catalogosglobal/edocivil
###
GET http://localhost:3001/api/catalogosglobal/edades


### CATALOGOS DINÁMICOS
GET {{baseUrl}}/6024878b19e804be07b07462

### AGREGA CATALOGOS
POST {{baseUrl}}
Content-Type: application/json

{
    "iglesia": "6024878b19e804be07b07462",
    "catalogos":[
        {
            "id": 0,
            "nombre": "Tipos de Miembros",
            "items":[
                {"tipo":"Miembro"},
                {"tipo":"Visita"},
                {"tipo":"En Proceso"},
                {"tipo":"VIP"}
            ]

        },
        {
            "id": 1,
            "nombre": "Tipos de Ministerios",
            "items":[
                {"tipo":"Alabanza"},
                {"tipo":"Maestros"},
                {"tipo":"Evangelismo"},
                {"tipo":"VIP"}
            ]

        },
        {
            "id": 2,
            "nombre": "Grupo Edades",
            "items":[
                {"tipo":"Adulto"},
                {"tipo":"Adolescente"},
                {"tipo":"Niño"}
            ]

        }
    ]
}


### ACTUALIZA  TIPO DE MIEMBRO
PUT {{baseUrl}}
Content-Type: application/json

{
    "tipo": "Miembro"
}

### BORRAR documento TIPO DE MIEMBRO
DELETE http://localhost:3001/api/catalogos/tipomiembros/604f903e97d9600d7928f522

