POST http://localhost:3001/api/login
Content-Type: application/json

{

"email": "julio.vidana@gmail.com",
 "password": "123123"

}

###
GET http://localhost:3001/api/login/profile
Content-Type: application/json 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwMmJmOGMyZTkxNzZiZTUwMDhlZjJjYyIsImVtYWlsIjoianVsaW8udmlkYW5hQGdtYWlsLmNvbSIsInJvbCI6InN1cGVyYWRtaW4iLCJpc3MiOiJhcGkuaWdsZXNpYXBwIiwiaWF0IjoxNjE4NzY2NzY3LCJleHAiOjE2MTg4NTMxNjd9.pEZzeprpGKu1Bn8PPyd1zWkl0qMtl6wTK6YvsJrsRD0

###
POST https://iglesiapp.herokuapp.com/api/login
Content-Type: application/json

{

"email": "julio.vidana@gmail.com",
 "password": "123123"

}