 @baseUrl = http://localhost:3001/api/notas
 @authToken = Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwN2M5NGJlYzk1MjA1ZmYyZDM3MGY4NyIsImVtYWlsIjoiY2VzYXJAZ21haWwuY29tIiwicm9sIjoiZWRpdG9yIiwiaXNzIjoiYXBpLmlnbGVzaWFwcCIsImlhdCI6MTYxODc4ODQ4MywiZXhwIjoxNjE4ODc0ODgzfQ.y3MmEMBRE_XDk0iEVvhbnlpK-CRhOoqlmxG0Fy6Z8Dk

### TRAE NOTAS POR PERSONA
GET {{baseUrl}}/6035ddb53530c334a10674fe
Authorization: {{authToken}}

### GUARDA NUEVA NOTA
POST {{baseUrl}}
Content-Type: application/json

{
    "nota": "Tercera Nota de prueba",
    "categoria":"General",
    "persona":"6035ddb53530c334a10674fe",
    "usuario": "602bf8c2e9176be5008ef2cc",
    "fecha": "2021-03-28T17:11:21.472Z",
    "iglesia":"6024878b19e804be07b07462"
}

### BORRAR NOTA
DELETE {{baseUrl}}/607868b3479de97cf0d919b3
Authorization: {{authToken}}
Content-Type: application/json

### TRAE NOTAS GLOBAL POR IGLESIA
GET {{baseUrl}}/global/6024878b19e804be07b07462
Authorization: {{authToken}}
Content-Type: application/json